name: VisaPay
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_credit_card: ^0.1.3
  cupertino_icons: ^0.1.3
  modal_progress_hud: ^0.1.3
  circular_profile_avatar: ^1.0.6
  share: ^0.6.4+3
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  animated_text_kit: ^2.2.0
  flappy_search_bar: ^1.7.2
  sqflite: ^1.3.1
  qr_flutter: ^3.2.0
  rich_alert: ^0.1.32

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: fonts/Signatra.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
        
  assets:
  - images/